export const browserCoreExamples = [
  "synurex browser status",
  "synurex browser start",
  "synurex browser stop",
  "synurex browser tabs",
  "synurex browser open https://example.com",
  "synurex browser focus abcd1234",
  "synurex browser close abcd1234",
  "synurex browser screenshot",
  "synurex browser screenshot --full-page",
  "synurex browser screenshot --ref 12",
  "synurex browser snapshot",
  "synurex browser snapshot --format aria --limit 200",
  "synurex browser snapshot --efficient",
  "synurex browser snapshot --labels",
];

export const browserActionExamples = [
  "synurex browser navigate https://example.com",
  "synurex browser resize 1280 720",
  "synurex browser click 12 --double",
  'Synurex browser type 23 "hello" --submit',
  "synurex browser press Enter",
  "synurex browser hover 44",
  "synurex browser drag 10 11",
  "synurex browser select 9 OptionA OptionB",
  "synurex browser upload /tmp/file.pdf",
  'Synurex browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "synurex browser dialog --accept",
  'Synurex browser wait --text "Done"',
  "synurex browser evaluate --fn '(el) => el.textContent' --ref 7",
  "synurex browser console --level error",
  "synurex browser pdf",
];
